stages:
  - test

services:
  - mysql:5.7
  - name: elasticsearch:7.2.0
    command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]

variables:
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_HOST: mysql
  MYSQL_DATABASE: bitrix
  MYSQL_USER: bitrix
  MYSQL_PASSWORD: bitrix
  ELASTICSEARCH_HOSTS: http://elasticsearch:9200

before_script:
  - apt-get update -yqq && apt-get install -yqq zip unzip
  - docker-php-ext-install mysqli
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - curl https://getcomposer.org/installer | php --
  - php composer.phar install --no-interaction
  - echo 'short_open_tag=1' >> $PHP_INI_DIR/php.ini
  - echo 'mbstring.func_overload=2' >> $PHP_INI_DIR/php.ini

PHP 7.1:
  stage: test
  image: php:7.1
  script: vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover=coverage.clover

PHP 7.2:
  stage: test
  image: php:7.2
  script: vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover=coverage.clover

PHP 7.3:
  stage: test
  image: php:7.3
  script: vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover